# shw2018 洪卫  modify 2019.08.01
# main menu navigation url and icon
# 配置菜单导航的名称、路径和图标icon.
menu:
  Index:
    url: /
    icon: fa-home
#  Tags:
#    url: /tags
#    icon: fa-tags
#  Categories:
#    url: /categories
#    icon: fa-bookmark
#  Archives:
#    url: /archives
#    icon: fa-archive
  AV:
    url: /AV
    icon: fa-music
  # List: 
  # url: /List
  # icon: fa-heartbeat
  # children: 
  #   -
  #     name: 音乐
  #     url: /List/music
  #     icon: fa-music
  #   -
  #     name: 视频
  #     url: /List/movies
  #     icon: fa-film
  Galleries:
    url: /galleries
    icon: fa-photo
  About:
    url: /about
    icon: fa-user-circle-o
#  Contact:
#    url: /contact
#    icon: fa-envelope
Friends:
  url: /friends
  icon: fa-address-book


# Index cover carousel configuration.
# 首页封面轮播图的相关配置.
cover:
  showPrevNext: true # 是否显示左右切换按钮. Whether to display the left and right toggle buttons.
  showIndicators: true # 是否显示指示器. # Whether to display the indicators
  autoLoop: true # 是否自动轮播. Whether it is automatically rotated.
  duration: 120 # 切换延迟时间. Switching delay time.
  intervalTime: 2500 # 自动切换下一张的间隔时间. Automatically switch the interval of the next one.

# index page dream text,
# 配置首页显示"梦想"的语句.
dream:
  enable: false
  showTitle: true
  title: 我的梦想
  text: 不是每个人都应该像我这样去建造一座水晶大教堂，但是每个人都应该拥有自己的梦想，设计自己的梦想，追求自己的梦想，实现自己的梦想。梦想是生命的灵魂，是心灵的灯塔，是引导人走向成功的信仰。有了崇高的梦想，只要矢志不渝地追求，梦想就会成为现实，奋斗就会变成壮举，生命就会创造奇迹。——罗伯·舒乐

# Whether to display the musics.
# 是否在首页显示音乐.
music:
  enable: true
  showTitle: false
  title: 听听音乐
  fixed: false # 开启吸底模式
  autoplay: false # 是否自动播放
  theme: '#542674'
  loop: 'all' # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'random' # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto' # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.6 # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: false # 列表默认折叠
  listMaxHeight: "197px" #列表最大高度

# Whether to display the videos.
# 是否在首页显示视频.
video:
  enable: false
  showTitle: false
  title: 看看视频
  url: https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4 # 必填
  pic:
  thumbnails:
  height: # 如：400
  autoplay: false # 是否自动播放
  theme: '#42b983'
  loop: true # 是否循环播放
  preload: 'auto' # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7


# Whether to display the title of the recommended posts
# 是否显示推荐文章的标题
recommend:
  showTitle: false

# Configure website favicon and LOGO
# 配置网站favicon和网站LOGO
favicon: https://raw.githubusercontent.com/8546KB/My_picture/master/20191207201027.png
logo: https://raw.githubusercontent.com/8546KB/My_picture/master/20191207201027.png

# The configuration of the second button in the home banner,
# including the display name of the button, the font awesome icon, and the hyperlink to the button.
# 首页 banner 中的第二个按钮的配置，包括按钮的显示名称、font awesome图标和按钮的超链接.
indexbtn:
  enable: true
  name: Github
  icon: fa-github-alt
  url: https://github.com/axh2018/

# The configurations of the second line of home banner
# icon/button will not show up if you leave the corresponding socialLink empty
# 首页 banner 中的第二行个人信息配置，留空即不启用
socialLink:
  qq: 1759895304
  github: axh2018
  email: 1759895304@qq.com
  zhihu: 8546-97

# Whether to activate the Post TOC, and Configure which title types are supported by TOC support.
# You can add `toc: false` to the Front-matter of a post to turn off the TOC.
# 是否激活文章 TOC 功能，并配置TOC支持选中哪些标题类型，这是全局配置。
# 可以在某篇文章的 Front-matter 中再加上`toc: false`，使该篇文章关闭TOC目录功能
toc:
  enable: false
  heading: h1, h2, h3, h4, h5
  showToggleBtn: true # 是否显示切换TOC目录展开收缩的按钮

# Whether the code is broken.
# 代码是否换行
code:
  break: true

# 是否激活文章末尾的打赏功能，默认激活（你替换为的你自己的微信、支付宝二维码图片、或者使用网络图片也可以）.
reward:
  enable: false
  title: 你的赏识是我前进的动力!
  wechat: /medias/reward/wechat.bmp
  alipay: /medias/reward/alipay.bmp

# Whether to activate the copyright information of the blog and author when copying the post content.
# minCharNumber: Approve copyright information by copying at least how many characters.
# 是否激活复制文章时追加博客和作者的版权信息.
copyright:
  enable: true
  minCharNumber: 120 # 至少复制多少个字符就追加版权信息.
  description: 本文章著作权归作者所有，任何形式的转载都请注明出处。

# Whether to activate the mathjax, this is a global configuration, but the post still does not open the mathjax rendering.
# Considering that the mathjax loading is time consuming,
# you also need to add `mathjax: true` to the Front-matter of the post that needs to be rendered.
# 是否激活mathjax数学公式，这是全局配置，但文章仍然不会都开启mathjax渲染，
# 考虑到mathjax加载比较耗时，你还需要在需要渲染的文章的Front-matter中再加上`mathjax: true`才行.
mathjax:
  enable: false
  cdn: https://cdn.bootcss.com/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Post word count, reading duration, site total word count.
# Before you activate, please confirm that you have installed the hexo-wordcount plugin,
# install the plugin command: `npm i --save hexo-wordcount`.
# 文章字数统计、阅读时长、总字数统计
# 激活前请确认你已经安装了 hexo-wordcount 插件，安装命令: `npm i --save hexo-wordcount`
wordCount:
  enable: true
  postWordCount: true
  min2read: true
  totalCount: true

# Whether to activate the 'love' effect of clicking on the page.
# 是否激活点击页面的'爱心'效果，默认激活.
clicklove:
  enable: true

# profile in about page, including avatars, career, and personal introductions.
# 在”关于”页面中配置个人信息，包括头像、职业和个人介绍.
profile:
  avatar: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAI4AAACOCAMAAADQI8A6AAAAaVBMVEX/////UV7/9/j/MEL/SVf/RFP/T1z/S1n/R1X/hY3/7u//+vr/ZnH/ipH/N0j/Kz//QE//mZ//zdD/3d//5uj/j5b/v8P/0tT/YGv/pKn/lJr/rLH/ub3/bXb/V2P/s7f/e4T/dH3/Izk4z7p0AAAHA0lEQVR4nO2c65KqOBCABXMDhA0Igiio+/4PuaioQNJJgISzVbv9a2oGwkenk76kmd3uf3Ekfl6ebpe0iOMgiOMivdxOZe7/CZIwvxZN61HEMGPoJaz7EVGvbYprHm7JcjwHbcIZIcQTpPsl40kbnI+boIRZgDijEpARFGUcBZlrJR3rCjMNyheJ4ap2qKPwViXIkKUnQkl1c6OiPG0xncPyForbNHcAw00nSVAR45aB8hqxZSxvYai2CHRp8ULNfDWE24slmKzlK2FeQLzNLMD4NVpgwDKhqF7tQLIW24F5Cl6poOi81mjGQvA5Wk4TPrhNmKfwx+JdMaOWrGYolC6csNM8h2AqBJ2W0JwTJzQdT3KeTxNYXFFTwcFMmKiwbsRD4cWsBRbdHermKfg+h6dwTNPxFOY0gdOZegs3tp+zc908BRuur1OyBY3nJUb7T+Zm9xOFIIP9OdTlLJMxCX2mfp10KR+VJV6Ke6nWf0UPcz9FKOdec4/T8+V2u5zT+N54nM94HfrQLfez6aIiiKHHpczDwYhRmJeXR/cHUyKuMefMbFERmlRpBrxalKVVYqgjrDQfvzUZhTDvXirjTL+8e0Z5EGlV49QGyunSJpMsJa+NEjNcw0NkSH8/IrVhPBfWxGQ8eLpa7aoivJlRBDg2+pSIttDdF+2qYu3VHOYp11abvXIgH8y1dszmx93hQ8dDWrkl6ux4UVBpEOTKrTnXbF6ELgq5O5es2YMIkqknVWuVsMUZZKZZ8SwV78nVdkzZiopIztRLlotjq5VDvFXZdeYp9SOqJ1QuK4LLNTS7XanM9Uk7XbE35bLCC634Jyf1+LfJ5ZVqdrnE1uZKqrJNWo0vPqriYzorKQIkuqteOBm7nlrl7BIrleFQ9cZotBWGlcLS8Ew/BclVYT6kGr6yKgjUB7SGogzDR2FhoNh0EmvHCioDZcOkVOGuWGyLZreL4bcmaIANL0JCLZ65HBXOlP+ec4ap0dzKkFICeAGzX/QSwDZmz3KeorAe+n1vhb+ytqzeolhcP7+Vw8xs6kxWyg02i+QTZVxhS8aWj+pCeIPjn922AJHpARg11Bx2gBc04GyxT3muAU1HnnRkcXNoAkU8dg26CwrpIoCTJ9K8r1Ak5lgyZN4kiBBCkwYIV8uW0+4ClAQSDR3B2fqk6zkYOY4dW09TfaaWeVLDKr/nX/gu8sDOmnjv1yvB6ZQFOs3P0JAsDvIHmTUXMyhF2EPfAfAJ3CqROFw23BQSif2MjGMv6g+OrPqjE3gvwKIlF8PRZB7kQNQDXEDj6fc4+AIuvL3/GD6NiNWHcGSIVOTNwKXVs8MZluiwwmaMIxjPeF3Qu4ADu60+24J3QTFInminEp420Y4YLMEhc78PxqBxSSxxZDuy0GxkO5JtNNxDT0OxDkfcN8rhaIkkN9WtLF+HA8dEEpzd/Te1TBaa+YffxiI7BVHgBAtwwt+uTKRu8sg/PFwWLGlxZk1WN16QPLu+WBIDTjt/vJwalqfS2smaidPZT11VVQHXNKIsqKpDKg9rtTjwQgdwVgmM0y90eBvcGOc9ubCT2BandxLXf4t23sEyHGBsi9MHGCV4ZLgpDiHvtQoHp9vi9IcBcOi+MU7/NDCx0eOEgizH6RMbeB/U4vj36jCSSpI8GOJ80z4wKdbiRI+ndxoI0pYYQJxvUgyWDPSTVUw2CaRtPAFxviUDsKCix5lmIfqKB4QzOAiAyk16nHxcXiNUe64D4QySDqgYZ7DQH6PZQg/tDRDOoBgHlSoNcMYlAFmJwRBnUKqECrkm2+Dw6MPkKAXAGRZyoTK30a78awTl+qkCcUZpAHAIYIQTpez1MoilJmVNAGd0CABUXQx9VhYk+31yNzuelONMKknyMoe5C9X7KjXOpHQjT+S38+jT4oT08HEznOnho/xodjMc4WhW6re2whEPrqXZ1lY4kq4HWdPDVjiSpgeZejbCkbWEyBpmtsGRN8xImpS3wQFal8Vmq01woGYr8TRlExyoFW23m6ajW+AQD7w0Y9vjqHq4Js1xe6vnslIcVZPnNF3/yz7NBEfdAjsJC93jqBuEJ+3TznF07dPjg3fXOAZNA8PWe8c4Bq33ow8T3OIYfZgw/GzDLY7ZZxuDj1qc4ph+1LLbxdwdzidn4TO6pvpYwyHOnA+iPp+LucOZ97lY/zGdM5yZH9N1EmN3OHhBt905cYWzrGf+hP62zdLJcb/sM9Vuf3aDs7gv3MU/IDmu6JmPrPP46wJM3yrQ+tGile8zFCtD2VKQrXGsKMimltebtEWY13BrxovsLoiXLAdyAPMedsG4i24yH3xenOKSpX9CaEgUhZbtF5BO/7ql1l3gXDEDiaLueZH05Z8gkfxPjuWtA/9lUN8f/8i/IftvyD/CUmD1DUWbuwAAAABJRU5ErkJggg==
  career: 江西师范大学 | 软件工程 | 编程 | Linux
  introduction: 我是江西师范大学软件工程学院2018级本科生。欢迎大家报考！

# config my projects informations in about page.
# If you don't want to display this `My Projects` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的项目"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myProjects:
  enable: true
  data:
    DeepLearning-500-questions:
      icon: fa-file-text-o
      iconBackground: 'linear-gradient(to bottom right, #29B6F6 0%, #1E88E5 100%)'
      url: https://github.com/axh2018/hexo_blog
      desc: 我的博客开源小项目



# config my skills informations in about page.
# If you don't want to display this `My Skills` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的技能"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
mySkills:
  enable: true
  data:
    C:
      background: 'linear-gradient(to right, #9900FF 0%, #CC66FF 100%)'
      percent: 60%
    Python:
      background: 'linear-gradient(to right, #2196F3 0%, #42A5F5 100%)'
      percent: 65%
    Java:
      background: 'linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)'
      percent: 50%
    SQL:
      background: 'linear-gradient(to right, #4CAF50 0%, #81C784 100%)'
      percent: 50%
    HTML:
      background: 'linear-gradient(to right, #FFEB3B 0%, #FFF176 100%)'
      percent: 70%
    JavaScript:
      background: 'linear-gradient(to right, #ec31ff 0%, #FFF176 100%)'
      percent: 50%

# config gallery of my photos in about page.
# If you don't want to display this `Gallery` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的相册"图片，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myGallery:
  enable: true
  data:
    - /medias/banner/0.jpg
    - /medias/banner/1.jpg
    - /medias/banner/2.jpg
    - /medias/banner/3.jpg
    - /medias/banner/4.jpg
    - /medias/banner/5.jpg
    - /medias/banner/6.jpg
    - /medias/banner/7.jpg
    - /medias/banner/8.jpg
    - /medias/banner/9.jpg
    - /medias/banner/10.jpg
    - /medias/banner/11.jpg
    - /medias/banner/12.jpg
    - /medias/banner/13.jpg
    - /medias/banner/14.jpg
    - /medias/banner/15.jpg
    - /medias/banner/16.jpg
    - /medias/banner/17.jpg
    - /medias/banner/18.jpg
    - /medias/banner/19.jpg
    - /medias/banner/20.jpg
    - /medias/banner/21.jpg
    - /medias/banner/22.jpg
    - /medias/banner/24.jpg
    - /medias/banner/24.jpg
    - /medias/banner/25.jpg
    - /medias/banner/26.jpg
    - /medias/banner/27.jpg
    - /medias/banner/28.jpg
    - /medias/banner/29.jpg
    - /medias/banner/30.jpg
    - /medias/banner/31.jpg
    - /medias/banner/32.jpg
    - /medias/banner/33.jpg
    - /medias/banner/34.jpg
    - /medias/banner/35.jpg
    - /medias/banner/36.jpg
    - /medias/banner/37.jpg
    - /medias/banner/38.jpg
    - /medias/banner/39.jpg
    - /medias/banner/40.jpg
    - /medias/banner/41.jpg
    - /medias/banner/42.jpg
    - /medias/banner/43.jpg
    - /medias/banner/44.jpg
    - /medias/banner/45.jpg
    - /medias/banner/46.jpg
    - /medias/banner/47.jpg
    - /medias/banner/48.jpg
    - /medias/banner/49.jpg
    - /medias/banner/50.jpg
    - /medias/banner/51.jpg
    - /medias/banner/52.jpg
    - /medias/banner/53.jpg
    - /medias/banner/54.jpg
    - /medias/banner/55.jpg
    - /medias/banner/56.jpg
    - /medias/banner/57.jpg
    - /medias/banner/58.jpg
    - /medias/banner/59.jpg
    - /medias/banner/60.jpg
    - /medias/banner/61.jpg
    - /medias/banner/62.jpg

# Whether to display post-calender in the `archive` page
# 设置在归档页面中是否显示'文章日历'控件
postCalendar: false

# the Gitalk config，default disabled
# Gitalk 评论模块的配置，默认为不激活
gitalk:
  enable: false
  owner: axh2018
  repo: axh018.github.io
  oauth:
    clientId:
    clientSecret:
  admin:
    - axh2018

# the Gitment config，default disabled
# Gitment 评论模块的配置，默认为不激活
gitment:
  enable: false
  owner:
  repo:
  oauth:
    clientId:
    clientSecret:

# disqus config, default disabled
# Disqus评论模块的配置，默认为不激活
disqus:
  enable: false
  shortname:

# Livere comment configuration, the default is not activated
# Livere 来必力评论模块的配置，默认为不激活
livere:
  enable: false
  uid:

# The configuration of the Valine comment module is not activated by default.
# To use it, activate the configuration item and set appId and appKey.
# Valine 评论模块的配置，默认为不激活，如要使用，就请激活该配置项，并设置 appId 和 appKey.
valine:
  enable: false
  appId:
  appKey:
  notify: true
  verify: true
  visitor: true
  avatar: 'mm' # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  pageSize: 10
  placeholder: 'just go go' # Comment Box placeholder

# Whether to display fork me on github icon and link, default true, You can change it to your repo address
# 配置是否在 header 中显示 fork me on github 的图标，默认为true，你可以修改为你的仓库地址.
githubLink:
  enable: true
  url: https://github.com/axh2018/axh2018.github.io
  title: Fork Me

# The password verification feature of read post. To use this feature,
# activate the configuration item and write the 'password' key and Cipher in the post's Front-matter.
# Note: In order to ensure that the original password will not be leaked to the web page,
# the password of the article must be encrypted by 'SHA256' so that it will not be cracked.
# 阅读文章的密码验证功能，如要使用此功能请激活该配置项，并在对应文章的Front-matter中写上'password'的键和加密后的密文即可.
# 请注意：为了保证密码原文不会被泄露到网页中，文章的密码必须是通过'SHA256'加密的，这样就不会被破解.
verifyPassword:
  enable: false
  promptMessage: 请输入访问本文章的密码
  errorMessage: 密码错误，将返回主页！

# busuanzi(http://busuanzi.ibruce.info/) website statistics
# 不蒜子(http://busuanzi.ibruce.info/) 网站统计
busuanziStatistics:
  enable: true
  totalTraffic: true # 总访问量
  totalNumberOfvisitors: true # 总人次

# Add google analytics configuration
# 添加 Google Analytics 配置
googleAnalytics:
  enable: true
  id: UA-144253917-1

# The used front-end library can be replaced with the corresponding CDN address as needed,
# If the specific version is not specified below, you can use the latest version.
# 使用到的前端库，可按需替换成对应的CDN地址，如果下面未指定具体的版本号，使用最新的版本即可.
libs:
  css:
    fontAwesome: /libs/awesome/css/font-awesome.min.css # V4.7.0
    materialize: /libs/materialize/materialize.min.css # 1.0.0
    aos: /libs/aos/aos.css
    animate: /libs/animate/animate.min.css # V3.5.1
    lightgallery: /libs/lightGallery/css/lightgallery.min.css # V1.6.11
    aplayer: /libs/aplayer/APlayer.min.css
    dplayer: /libs/dplayer/DPlayer.min.css
    gitalk: /libs/gitalk/gitalk.css
    jqcloud: /libs/jqcloud/jqcloud.css
    tocbot: /libs/tocbot/tocbot.css

    fancybox: https://cdn.staticfile.org/fancybox/3.5.7/jquery.fancybox.min.css
    justifiedGallery: https://cdn.staticfile.org/justifiedGallery/3.7.0/css/justifiedGallery.min.css
    share: /libs/share/css/share.min.css
    my: /css/my.css
    matery: /css/matery.css
  js:
    jquery: /libs/jquery/jquery-2.2.0.min.js
    materialize: /libs/materialize/materialize.min.js # 1.0.0
    masonry: /libs/masonry/masonry.pkgd.min.js # v4.0.0
    aos: /libs/aos/aos.js
    scrollProgress: /libs/scrollprogress/scrollProgress.min.js
    lightgallery: /libs/lightGallery/js/lightgallery-all.min.js # V1.6.11
    clicklove: /libs/others/clicklove.js
    busuanzi: /libs/others/busuanzi.pure.mini.js
    aplayer: /libs/aplayer/APlayer.min.js
    dplayer: /libs/dplayer/DPlayer.min.js
    crypto: /libs/cryptojs/crypto-js.min.js
    echarts: /libs/echarts/echarts.min.js
    gitalk: /libs/gitalk/gitalk.min.js
    jqcloud: /libs/jqcloud/jqcloud-1.0.4.min.js
    tocbot: /libs/tocbot/tocbot.min.js

    fancybox: https://cdn.staticfile.org/fancybox/3.5.7/jquery.fancybox.min.js
    justifiedGallery: https://cdn.staticfile.org/justifiedGallery/3.7.0/js/jquery.justifiedGallery.min.js
    lazyload: /libs/lazyload/jquery.lazyload.js
    share: /libs/share/js/social-share.min.js
    matery: /js/matery.js
    search: /js/search.js

    sakura: /js/sakura.js
    fireworks: /js/fireworks.js
    wenzi: /js/wenzi.js
    xuehuapiaoluo: /js/xuehuapiaoluo.js
    instant.page: /js/instant.page.js

    canvas_nest: /libs/background/canvas-nest.js
    ribbon: /libs/background/ribbon.min.js
    ribbon_dynamic: /libs/background/ribbon-dynamic.js

# The post featured images that needs to be displayed when there is no image.
# 无文章特色图片时需要显示的文章特色图片.
featureImages: 
- /medias/featureimages/0.jpg
- /medias/featureimages/1.jpg
- /medias/featureimages/2.jpg
- /medias/featureimages/3.jpg
- /medias/featureimages/4.jpg
- /medias/featureimages/5.jpg
- /medias/featureimages/6.jpg
- /medias/featureimages/7.jpg
- /medias/featureimages/8.jpg
- /medias/featureimages/9.jpg
- /medias/featureimages/10.jpg
- /medias/featureimages/11.jpg
- /medias/featureimages/12.jpg
- /medias/featureimages/13.jpg
- /medias/featureimages/14.jpg
- /medias/featureimages/15.jpg
- /medias/featureimages/16.jpg
- /medias/featureimages/17.jpg
- /medias/featureimages/18.jpg
- /medias/featureimages/19.jpg
- /medias/featureimages/20.jpg
- /medias/featureimages/21.jpg
- /medias/featureimages/22.jpg
- /medias/featureimages/23.jpg
- /medias/featureimages/24.jpg
- /medias/featureimages/25.jpg
- /medias/featureimages/26.jpg
- /medias/featureimages/27.jpg
- /medias/featureimages/28.jpg
- /medias/featureimages/29.jpg
- /medias/featureimages/30.jpg
- /medias/featureimages/31.jpg
- /medias/featureimages/32.jpg
- /medias/featureimages/33.jpg
- /medias/featureimages/34.jpg
- /medias/featureimages/35.jpg
- /medias/featureimages/36.jpg
- /medias/featureimages/37.jpg
- /medias/featureimages/38.jpg
- /medias/featureimages/39.jpg
- /medias/featureimages/40.jpg
- /medias/featureimages/41.jpg
- /medias/featureimages/42.jpg
- /medias/featureimages/43.jpg
- /medias/featureimages/44.jpg

  # default configs that the default policy for every articles/posts
  # default 配置文章的默认转载规则

  # you can define reprint policy for a single article in the front-matter of the specific md file using this key: reprintPolicy
  # 您可以使用在文章md文件的 front-matter 中指定 reprintPolicy 来给单个文章配置转载规则

  # 可用的转载规则有（available reprint policies are）：
  # 这些转载规则的意义请参考(you can refer to this link FMI)：https://creativecommons.org/choose/?lang=zh
  # cc_by（知识共享署名 4.0 国际许可协议 Creative Commons Attribution-NoDerivatives 4.0 International License）
  # cc_by_nd（知识共享署名-禁止演绎 4.0 国际许可协议 Creative Commons Attribution-NoDerivatives 4.0 International License）
  # cc_by_sa（知识共享署名-相同方式共享 4.0 国际许可协议 Creative Commons Attribution-ShareAlike 4.0 International License）
  # cc_by_nc（知识共享署名-非商业性使用 4.0 国际许可协议 Creative Commons Attribution-NoDerivatives 4.0 International License）
  # cc_by_nc_nd（知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议 Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License）
  # cc_by_nc_sa（知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议 Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License）

  # cc0（CC0 1.0 通用 (CC0 1.0) 公共领域贡献 CC0 1.0 Universal (CC0 1.0) Public Domain Dedication） https://creativecommons.org/publicdomain/zero/1.0/deed.zh

  # noreprint（不允许转载 not allowed to reprint）
  # pay（付费转载 pay for reprinting）

reprint:
  enable: fasle # whether enable reprint section 是否启用“转载规则限定模块”
  default: cc_by

# Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO
baidu_push: true


# 页面樱花飘落动效
sakura:
  enable: true

# 鼠标点击烟花爆炸动效
fireworks:
  enable: true


# 天气控件 Weather Widget
weather:
  enable: true

# 鼠标点击文字特效 
wenzi:
  enable: true

# 背景雪花飘落特效
xuehuapiaoluo:
  enable: true

# Tidio online contact 
tidio:
  enable: false
  public_key:

#背景canvas-nest
canvas_nest:
  enable: true
  color: 0,0,255 #线条颜色, 默认: '0,0,0' ；三个数字分别为(R,G,B)，注意用,分割
  pointColor: 0,0,255 #交点颜色, 默认: '0,0,0' ；三个数字分别为(R,G,B)，注意用,分割
  opacity: 0.8 # 线条透明度（0~1）, 默认: 0.5
  zIndex: -1 # 背景的z-index属性，css属性用于控制所在层的位置, 默认: -1
  count: 150 # 线条的总数量, 默认: 99

#背景静止彩带
ribbon:
  enable: false
  size: 150 #彩带大小, 默认: 90
  alpha: 0.6 #彩带透明度 (0 ~ 1), 默认: 0.6
  zIndex: -1 #背景的z-index属性，css属性用于控制所在层的位置, 默认: -1
  click_to_change: false  #设置是否每次点击都更换彩带

#背景动态彩带
ribbon_dynamic:
  enable: true 




